### ISSUE TITLE
Crashes your game in currents chunks.

### ISSUE THREAD

**Issue by BruhKidBruh** [Trivaxy/Tiny-Item-Animations#8] opened 2024-02-05 11:34 UTC
This is odd because of all mods I haven't I did not expect it was this one to have to this issue. If you go into that chunk it will chunk ban you all you need to do is uninstall it but I am a but sad that i cant use this mod

**Comment by Trivaxy** [comment] 2024-02-05 14:47
Are you sure that this mod is the cause? 
Please send your mod list and your crash logs. TIA does not touch anything related to chunks at all.

**Comment by Trivaxy** [comment] 2024-03-23 06:04
Closing due to lack of info.

**Closed as completed by Trivaxy** 2024-03-23 06:04 UTC
